# Generated by Django 4.1.5 on 2023-01-15 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_home_greetings_1_alter_home_greetings_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='uploaded',
            new_name='updated',
        ),
    ]
