# Generated by Django 4.1.5 on 2023-01-15 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_uploaded_home_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='uploaded',
            new_name='updated',
        ),
    ]
